Add base for shop menu
TiagoFar78/PrisonEscape pull request #156
Opened 2024-04-17 20:52 UTC by iquelli

Closes #43, #108

2024-04-17 23:02 UTC, TiagoFar78 reviewed
I liked that you created menus package, but I think Chest and Vault classes should stay on prisonbuilding package. They are more of a block than a menu. They just happen to have a menu to represent them.

2024-04-17 23:02 UTC, TiagoFar78 commented on src/main/java/net/tiagofar78/prisonescape/menus/Shop.java
> +        MessageLanguageManager messages = MessageLanguageManager.getInstanceByPlayer(player.getName());
let returnCode variable be right before its if. Do this line a little bit above and with a space before and after.

2024-04-18 13:38 UTC, iquelli commented on src/main/java/net/tiagofar78/prisonescape/menus/Shop.java
> +        if (!(item instanceof Buyable)) {
just used the interface to avoid adding a function that most items won't use

2024-04-18 15:31 UTC, TiagoFar78 commented on src/main/java/net/tiagofar78/prisonescape/menus/Shop.java
> +        if (returnCode == -1) {
4 items, the same as a prisioner. Special items do not count as items in inventory.

2024-04-18 20:43 UTC, iquelli commented
> I liked that you created menus package, but I think Chest and Vault classes should stay on prisonbuilding package. They are more of a block than a menu. They just happen to have a menu to represent them.

But the part that's implemented in the class is the menu, not exactly anything related to where they are in the prison. Maybe we can change the nome of the classes to ChestMenu, Vault Menu and Shop Menu instead?

2024-04-18 20:46 UTC, iquelli commented
I'll change it back for now then. But what about clickable and ClickReturnAction?

2024-04-19 14:43 UTC, TiagoFar78 commented
> But what about clickable and ClickReturnAction, can I leave them in menu package?

Yes, and let Shop too.



> Think we could name the classes VaultMenu instead for example? Not sure.

I don't think it is a good idea to change Vault and Chests name. Maybe the best ideia is to create a new class named VaultMenu and doing menu related things there. And in this case Vault would have a VaultMenu.

However, this is not that relevant and we don't have to worry that much about it since it is just a question of where to place classes. You can leave the code as it is right now.

2024-04-19 14:53 UTC, TiagoFar78 reviewed
good job!

2024-04-19 14:53 UTC, TiagoFar78 commented on src/main/java/net/tiagofar78/prisonescape/items/Buyable.java
I think it would be a good ideia to add a boolean isBuyable() so you will be forced to implement that method when implementing this interface.

2024-04-19 18:51 UTC, iquelli commented on src/main/java/net/tiagofar78/prisonescape/items/Buyable.java
yeah I added

2024-04-21 01:07 UTC, TiagoFar78 requested changes

2024-04-21 01:07 UTC, TiagoFar78 commented on src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeGame.java
> +        player.removeItem(slot);
Convert the slot to an index

2024-04-21 16:13 UTC, TiagoFar78 approved these changes

2024-04-21 16:14 UTC, merged